import React, { FC } from "react";
import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";

import { PageWithLayoutType } from "../interfaces";
import { UserLayout } from "../components/";

const Page: FC = () => {
  return (
    <div>
      <Head>
        <title>Crono app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

(Page as PageWithLayoutType).layout = UserLayout;

export default Page;
