import * as React from "react";
import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";

import { NextPageWithLayout } from "../interfaces";
import { UserLayout } from "../components/";

const Page: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Crono app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};

export default Page;
