import * as React from "react";
import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";

import { NextPageWithLayout } from "../../interfaces";
import { OrganizerLayout } from "../../components";

const OrganizerPage: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Crono app | Admin </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

OrganizerPage.getLayout = function getLayout(page: ReactElement) {
  return <OrganizerLayout>{page}</OrganizerLayout>;
};

export default OrganizerPage;
