import React, { FC } from "react";
import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";

import { PageWithLayoutType, User } from "../../interfaces";
import { OrganizerLayout } from "../../components";
import { getUserService } from "../../services";

interface Props {
  user: User;
}

const OrganizerPage: FC<Props> = ({ user }) => {
  return (
    <div>
      <Head>
        <title>Crono app | Admin </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.name}
    </div>
  );
};

export async function getServerSideProps() {
  const user = await getUserService();
  return { props: { user } };
}

(OrganizerPage as PageWithLayoutType).layout = OrganizerLayout;

export default OrganizerPage;
