import * as React from "react";
import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Button from "@mui/material/Button";

import { NextPageWithLayout } from "../interfaces";
import { OrganizerLayout } from "../components/layout/organizer-layout";

const OrganizerPage: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Crono app | Admin </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Dame todo tu amor pony</h1>
        <Button variant="contained">Hello World</Button>
      </main>
    </div>
  );
};

OrganizerPage.getLayout = function getLayout(page: ReactElement) {
  return <OrganizerLayout>{page}</OrganizerLayout>;
};

export default OrganizerPage;
